parameters:
    # how many days privacy banner should be hidden when user accepts policy?
    ez_privacy_cookie.days: 365
    # name to be used to store cookie status
    ez_privacy_cookie.cookie_name: privacyCookieAccepted
    # banner description
    ez_privacy_cookie.banner_caption: Cookies help us create a good experience. By using our website, you agree to our use of cookies.
    # banner policy link caption
    ez_privacy_cookie.banner_link_text: Learn more
    # banner policy address
    ez_privacy_cookie.banner_link_url: ~
